- packages/flame/CHANGELOG.md
- packages/flame/src/Alert/Alert.test.tsx
- packages/flame/src/Alert/Alert.tsx
- packages/flame/src/Alert/README.md
- packages/flame/src/Alert/__snapshots__/Alert.test.tsx.snap
- packages/flame/src/Alert/index.tsx
- packages/flame/src/Alert/story.tsx
The current designs spec'd out for the `<Alert />` component it does not easily allow you to pass an icon for it. In order for devs to add these icons, they will need to completely ignore the `title` prop and implement the entire `<Alert />` body themselves (as proven by the implement within the internal design system documentation).
> Add <Alert /> `icon` prop

- packages/flame/src/Alert/README.md
Documenting what was added in #15.
- I have prepared [CHANGELOGs](https://github.com/lightspeed/flame/blob/master/.github/CONTRIBUTING.md#git-workflow) for release
- I have tested my changes on [supported browsers](https://browserl.ist/?q=%3E0.25%25%2C+not+op_mini+all%2C+not+ie+%3C%3D+11)
- I have added tests that prove my fix is effective or that my feature works
- When approved, I have run [visual regression tests](https://github.com/lightspeed/flame/blob/master/.github/CONTRIBUTING.md#running-visual-regression-tests), got it approved and [posted a link](https://percy.io/Lightspeed/flame)
> Add Alert with Icon example in docs

- codecov.yml
- packages/flame/src/Core/__tests__/index.test.tsx
Make it `90%` (currently at `~89%` on the repo) instead of `auto`. See https://docs.codecov.io/docs/commit-status#section-target for more info.
- Codecov commit status should show in the GitHub status checks
- I have prepared [CHANGELOGs](https://github.com/lightspeed/flame/blob/master/.github/CONTRIBUTING.md#git-workflow) for release
- I have tested my changes on [supported browsers](https://browserl.ist/?q=%3E0.25%25%2C+not+op_mini+all%2C+not+ie+%3C%3D+11)
- When approved, I have run [visual regression tests](https://github.com/lightspeed/flame/blob/master/.github/CONTRIBUTING.md#running-visual-regression-tests), got it approved and [posted a link](https://percy.io/Lightspeed/flame)
> Update Codecov target value

- packages/flame/CHANGELOG.md
- packages/flame/src/Badge/Badge.tsx
For some reason, extending a component with emotion pumps wonky types with the `opacity` prop. Go figure...
> Fix weird typing generation caused by emotion + TS

- packages/flame/CHANGELOG.md
- packages/flame/src/Checkbox/Checkbox.tsx
- packages/flame/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/flame/src/Checkbox/story.tsx
- packages/flame/src/Radio/Radio.tsx
- packages/flame/src/Radio/__snapshots__/Radio.test.tsx.snap
- packages/flame/src/Radio/story.tsx
- stories/helpers/percy.ts
Added some styled-system props and used the whole array notation to ensure the right values get used in mobile.
Needed to go with hard coded values instead of theme values to match up proposed design specs. 6 point scale means we cannot reliably get the values for 1rem, so this will do for now.
> Better mobile responsiveness for Checkbox/Radio

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
Provide a Flame starter CodeSandbox, helpful for reproducing/debugging new issues.
> Add a CodeSandbox starter for new bug issues

- packages/flame/src/Alert/Alert.tsx
- packages/flame/src/Alert/__snapshots__/Alert.test.tsx.snap
- packages/flame/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
- packages/flame/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/flame/src/Icon/__tests__/__snapshots__/Icon.test.tsx.snap
- packages/flame/src/Icon/utils/iconFactory.tsx
- packages/flame/src/Spinner/__snapshots__/Spinner.test.tsx.snap
- packages/flame/src/Switch/__snapshots__/Switch.test.tsx.snap
- packages/flame/src/Tag/__snapshots__/Tag.test.tsx.snap
Both will now resize appropriately in their mobile breakpoints. Mostly just adjusting the size of fonts
> Mobile friendly Alert & Icon

- .github/workflows/publish-lerna.yml
- .github/workflows/publish-mainline.yml
Let's speed up GitHub Actions workflows ("Publish mainline" and "Publish lerna") by taking advantage of the newly added [caching dependencies](https://help.github.com/en/github/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows) feature.
- When merged to `master`, "Publish lerna" and "Publish mainline" workflows should first install deps from fresh, then, on subsequent merges, it should use the `yarn` cached version
> Enable GitHub Actions caching dependencies

- packages/flame/CHANGELOG.md
- packages/flame/src/Dropdown/Dropdown.test.tsx
- packages/flame/src/Dropdown/Dropdown.tsx
- packages/flame/src/Input/Input.tsx
- packages/flame/src/InputGroup/InputGroup.tsx
Passing an onClick handle on the Dropdown would override the toggle function. Now, we will always trigger the toggle, even when an onClick handler is passed.
Additionally, the InputGroup has been typed properly.
> Properly type InputGroup. Pass onClick callback to dropdown toggle

- packages/flame/CHANGELOG.md
- packages/flame/src/InputGroup/InputGroup.tsx
Funky scenarios where the child can be null which causes the InputGroup to go nuts. Bailing early will prevent issues caused by attempting to clone a null child.
> InputGroup early return if child is null

- packages/flame/CHANGELOG.md
- packages/flame/src/Input/Input.test.tsx
- packages/flame/src/Input/Input.tsx
Input status null check to prevent crashes
- Set input status to null
> Input status null check to prevent crashes

- codecov.yml
- packages/flame/CHANGELOG.md
- packages/flame/src/Group/Group.tsx
- packages/flame/src/Input/Input.tsx
Things are getting a bit too noisy. I'll instead do a post on the upcoming changes and plan a proper migration guide instead of polluting the console.
> Removed excessive console.warn from Group and Input

- README.md
- packages/flame/CHANGELOG.md
- packages/flame/src/Core/index.tsx
Read why in https://github.com/lightspeed/flame/issues/49.
> Remove FlameFonts from install docs, mark as deprecated

- package.json
- packages/flame/package.json
- packages/flame/src/Checkbox/index.tsx
- packages/flame/src/Core/index.tsx
- packages/flame/src/Switch/Switch.tsx
- packages/flame/src/Switch/__snapshots__/Switch.test.tsx.snap
- packages/flame/src/Switch/story.tsx
- yarn.lock
Switch will now properly resize on mobile devices.
I've also taken the time to leverage `emotion`'s css props and `styled-system/css` to create these styles. This should lead into a somewhat more maintainable codebase, as well as reduce the unnecessary HOC wrapping caused by `emotion/styled`
> Make switch more mobile friendly

- .github/workflows/percy-snapshot.yml
See https://docs.percy.io/docs/github-actions. For some reason snapshots on `master` are detected as `HEAD`, thus won't get auto-approved. Let's see if using the official GitHub Action fixes it.
> Use official Percy GitHub Action for visual regression snapshots

- .github/workflows/publish-mainline.yml
- packages/flame/CHANGELOG.md
- packages/flame/src/Alert/Alert.tsx
Github action to publish mainline was not using `yarn release`. Simply leverage it and do a small dummy change
> Force update to trigger github action

- package.json
- packages/flame/CHANGELOG.md
- packages/flame/package.json
- yarn.lock
Upgrading `@types/react` was not a good idea, it created issues with packages relying on Flame. Reverted back to `16.8.23` and use `resolutions` to force all sub-dependencies to also use this version. This is needed because `@storybook/*` packages have `@types/react@*` as deps.
- CI (type-checking mainly) should still pass ✅
> Revert @types/react package update, use locked version

- packages/flame/CHANGELOG.md
- packages/flame/scripts/docgen.js
- packages/flame/src/Alert/Alert.tsx
- packages/flame/src/Button/Button.tsx
- packages/flame/src/Checkbox/Checkbox.tsx
- packages/flame/src/Dialog/Dialog.tsx
- packages/flame/src/Dropdown/Dropdown.tsx
- packages/flame/src/Input/Input.tsx
- packages/flame/src/InputGroup/InputGroup.tsx
- packages/flame/src/Popover/Popover.tsx
- packages/flame/src/Progress/Progress.tsx
- packages/flame/src/Radio/Radio.tsx
- packages/flame/src/Switch/Switch.tsx
- packages/flame/src/Tab/Tab.tsx
- packages/flame/src/Tag/Tag.tsx
- packages/flame/src/Tag/examples/TagList.tsx
- packages/flame/src/Text/Text.tsx
- packages/flame/src/Text/__snapshots__/Text.test.tsx.snap
- packages/flame/src/Text/story.tsx
- packages/flame/src/Tooltip/Tooltip.tsx
Docgen script needed to be adjusted to properly concatenate the types together.
I've also taken the time to re-document certain things, as we were missing tsdocs for some components.
Additionally, I needed to do some adjustments to the exports of some components. Nothing major, they still are all named exports, however we cannot leverage the `export {}` notation, as that throws the parser into a fit. This is especially problematic with components that have multiple sub-components. Luckily, no breaking changes and it was quite simply to add in.
I've also previewed the changes directly in gatsby to ensure that the outputs are ok. We should be gucci now.
> Adjust docgen script, fix documentations for components

- packages/flame/CHANGELOG.md
- packages/flame/src/Checkbox/Checkbox.test.tsx
- packages/flame/src/Checkbox/Checkbox.tsx
Need to forward the indeterminate state to the component. ez-pz
closes #72 
- Checkout branch, run `yarn test`
> Handle checkbox indeterminate state at the DOM level

- packages/flame/CHANGELOG.md
- packages/flame/src/Layout/examples/story.tsx
- packages/flame/src/Layout/index.tsx
- packages/flame/themes/flame/colors.ts
Opening in favor of #78. Also updating AnnotatedLayout description text color to use `textDimmed` instead of the hard-coded `gray-300` value.
> Update textDimmed color alias + apply to AnnotatedLayout description

- .github/workflows/publish-lerna.yml
- .github/workflows/publish-mainline.yml
So that we can do `rc` releases from `next`.
> Enable publish workflow on next branch

- packages/flame/CHANGELOG.md
- packages/flame/src/Alert/Alert.tsx
- packages/flame/src/Alert/AlertInCard.tsx
Line height was borking up in DSD.
Force set it to normalize to preserve proper styling.
> Adjust line-height in Alert to be normal.

- packages/flame/CHANGELOG.md
- packages/flame/src/Alert/Alert.tsx
- packages/flame/src/Alert/AlertInCard.tsx
Which problem(s) does it solve and how? What does this PR add?
> Fix Alert and AlertInCard typing. Allow empty title

- packages/flame/CHANGELOG.md
- packages/flame/src/Dropdown/Dropdown.tsx
- packages/flame/src/Popover/Popover.tsx
- packages/flame/src/Tooltip/Tooltip.tsx
- packages/flame/src/hooks/useOnClickOutside.ts
Made it so that active poppers are updated whenever an outside event is triggered (AKA, update when clicked outside and when its active).
I've also updated the useOnClickOutside to not prematurely destroy event listeners. We do this by saving the handler callback as a ref and then using that one inside the effect function.
Closes #103 
> Force Update active poppers. Fix clickOutside handler

- packages/flame/CHANGELOG.md
- packages/flame/src/Toaster/Toaster.tsx
- packages/flame/src/Toaster/story.tsx
Lower z-index meant the toaster was getting stuck behind the modal overlay.
> Set higher zIndex for ToasterContainer

- netlify.toml
- package.json
- packages/flame/CHANGELOG.md
- packages/flame/src/Badge/next/Badge.tsx
- packages/flame/src/Badge/next/index.tsx
- packages/flame/src/Badge/story.tsx
- packages/flame/themes/dark/components/badge.ts
- packages/flame/themes/dark/index.ts
- packages/flame/themes/flame/components/badge.ts
- packages/flame/themes/flame/index.ts
- packages/flame/themes/oldskool/components/badge.ts
- packages/flame/themes/oldskool/index.ts
- packages/flame/typings/flame/index.d.ts
Badge is yet another one of those components that require an overhaul.
I'm introducing the concept of the "next" folder. Whenever we are about to introduce breaking changes to existing components, we will introduce the future component into the corresponding "next" folder. Please note that components within this folder are usually experimental and are subject to changes that might not be documented.
For the most part, they `should` be feature complete, so you shouldn't have the rug pulled from underneath too often. Since we want to lock release cycles on a more regular basis (something like 3 month cycle), this'll make progressive migration a bit easier.
The instant we change to a different major version, the `next/${component}` will be wiped clean, as that component will replace whatever …
> Add next/Badge component

- packages/flame/CHANGELOG.md
- packages/flame/src/Badge/next/Badge.tsx
Types were not being exported for badges, which can be annoying when trying to build on-top of this component.
Simply export the types.
> Export typing for next/Badge

- .github/workflows/chromatic-label.yml
- .github/workflows/chromatic.yml
- .github/workflows/publish-lerna.yml
- .github/workflows/publish-mainline.yml
Publishing scripts were being ran on every commit on master/next.
Technically, we only want to publish on new tag, not on commits.
> Use tags as target for publish action. Snapshot label for visual diffing

- packages/flame/CHANGELOG.md
- packages/flame/scripts/build-themes.ts
Typings was a bit too aggressive for themeGet. Set the theme as optional.
> Loosen typings for themeGet

- .github/workflows/chromatic-label.yml
- .github/workflows/test.yml
- packages/flame/CHANGELOG.md
- packages/flame/package.json
- yarn.lock
With the upgrade to React 17, the popover closes imminently after opening. I've found [this issue](https://github.com/popperjs/react-popper/issues/392) in the `react-popper` library. The issue led to the[ 2.2.4 release](https://github.com/popperjs/react-popper/releases/tag/v2.2.4) of `react-popper` which hopefully fixes the auto close issue.
> Upgraded react-popper to 2.2.4
